### ISSUE TITLE
Singularity

### ISSUE THREAD

**Issue by GuillaumeHolley** [fenderglass/hapdup#1]
Hi,

Thank you for this tool, I am really excited to try it! Would it be possible to have hapdup available as a Singularity image or to have the Docker image available online in a container repo (such that it can be converted to a Singularity image with a `singularity pull`)?

Thanks,
Guillaume

**Comment by kishwarshafin** [comment]
@GuillaumeHolley , 

The docker is available on docker hub:
```bash
cd directory_with_assembly_and_alignment
HD_DIR=`pwd`
docker run -v $HD_DIR:$HD_DIR --ipc=host -u `id -u`:`id -g` mkolmogo/hapdup:0.2 hapdup --assembly $HD_DIR/assembly.fasta --bam $HD_DIR/lr_mapping.bam --out-dir $HD_DIR/hapdup -t 64
```
You can use singularity similarly as you use for PEPPER-Margin-DeepVariant

**Comment by fenderglass** [comment]
Thanks @kishwarshafin !

@GuillaumeHolley let us know if you have any issues - I will update the manual soon to reflect this.

**Comment by GuillaumeHolley** [comment]
Thanks @kishwarshafin @fenderglass,

I just did a `singularity pull docker://mkolmogo/hapdup:0.2` to pull the Singularity image out of Docker Hub.

Guillaume
