### ISSUE TITLE
Super cool tool! Maybe in the README mention that FASTQ files are required if using the container

### ISSUE THREAD

**Issue by jelber2** [fenderglass/hapdup#15]
As far as know, inputting FASTA reads aligned to the reference as the bam file will result in Pepper failing to find any variants using the default settings of the Docker/Singularity container as the config for Pepper requires a minimum base quality setting.

**Comment by fenderglass** [comment]
Hi,

I think it should work with fasta in theory. Could you give a specific error output that you are getting?

**Comment by jelber2** [comment]
Hmmm. I was getting issues with PEPPER generating empty VCF files for input to margin. I simply ran Singularity. Deleted the pepper directory, restarted, and now it is working as far as I know?

**Comment by jelber2** [comment]
I will close this.
