### ISSUE TITLE
Docker installation problem

### ISSUE THREAD

**Issue by rpzhao** [fenderglass/hapdup#16]
I followed the tutorial and used Docker to install. The following question arises.
HD_DIR=`pwd`
docker run -v $HD_DIR:$HD_DIR -u `id -u`:`id -g` mkolmogo/hapdup:0.7 \
hapdup --assembly a.contigs.fasta --bam lr_mapping.bam --out-dir hapdup-1 -t 2 --rtype hifi
Traceback (most recent call last):
  File "/usr/local/bin/hapdup", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/hapdup/main.py", line 102, in main
    os.mkdir(args.out_dir)
PermissionError: [Errno 13] Permission denied: 'hapdup-1'

**Comment by rpzhao** [comment]
I solved the problem.It simply adds the absolute path to each file.Thanks!

**Comment by andzandz11** [comment]
I get the same error.
