### ISSUE TITLE
non haploid assembly as input

### ISSUE THREAD

**Issue by kallekarlhugo** [fenderglass/Hapdup#2]
Hi, 
Is it a requirement that the input assembly is completely haploid when you start? If the draft assembly has some remaining duplication (as measured by busco or Kmer spectra) would you recommend purging those first using for example purge_dups? 

Thanks

**Comment by fenderglass** [comment]
Good question - yes, we assume a completely haploid assembly, and it is a good idea to use purge_dups. I will add this to the manual.

Mikhail
