### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by MichelMoser** [fenderglass/hapdup#4]
Hi, 

I guess, currently there is no GPU allowance for the PEPPER step in the hapdup pipeline? 

Is the speed benefit too small to implement it for human sized genomes? 

Cheers, 
Michel

**Comment by MichelMoser** [comment]
i see you disabled CUDA to redue image space. fair move =)

**Comment by fenderglass** [comment]
Yes, PEPPER supports GPU, but all other tools don't. So the speed gain is overall little, and currently does not worth added complexity.
