### ISSUE TITLE
Changing `pepper_variant`  variant calling mode from ONT to HiFi

### ISSUE THREAD

**Issue by aseetharam** [fenderglass/hapdup#5]
Hello, 

Thanks for this program. I was wondering if there is an option to change the variant calling mode to hifi data instead of the default ONT mode? 

Thanks,

**Comment by fenderglass** [comment]
Release 0.4 now supports HiFi via `--rtype hifi` option. Please let us know if you have any issues.

**Comment by aseetharam** [comment]
Thanks very much!
