### ISSUE TITLE
Unable to assemble to chromosomes

### ISSUE THREAD

**Issue by tongyin121** [fenderglass/hapdup#6]
Hi,
I got a problem that the final haplotype files were all made up of contigs without chromosomes. 
could you please help me resolve this problem?
Thanks

**Comment by fenderglass** [comment]
Hi,

HapDup does not alter assembly structure/contiguity. If you original assembly was fragmented, HapDup haplotypes will retain the same fragmentation.

**Comment by tongyin121** [comment]
So that is the problem I met. The original assembly had all chromosomes ,but the final haplotype files did not. I am confused about this. Could you please tell me the reason of this problem.
Thanks.

**Comment by tongyin121** [comment]
Thank you for your reply. I know how to deal with this problem.
