### ISSUE TITLE
Using Pepper-MARGIN r0.7?

### ISSUE THREAD

**Issue by GuillaumeHolley** [fenderglass/hapdup#9]
Hi,

Would it be possible to include the latest version of Pepper-MARGIN (r0.7) in hapdup? I haven't been able to run hapdup on my data so far because of some issues in Pepper-MARGIN r0.6 (now solved in r0.7).

Thank you!

Guillaume

**Comment by fenderglass** [comment]
Hi,

Sure - will do within the next couple of weeks (expect to be very busy within the next few days).

**Comment by GuillaumeHolley** [comment]
Hi @fenderglass,

I just thought about the fact that Pepper-MARGIN r0.7 offers the possibility to input custom-made models for PEPPER-SNP, PEPPER-HP and DeepVariant. It would be great if you could also include these options in HapDup too when you find the time to update HapDup. I know you are very busy at the moment so no hurry, it's more of a suggestion rather than a "feature request" :)

Thanks!
Guillaume

**Comment by fenderglass** [comment]
The 0.5 release is now updated to PEPPER 0.7. I also added an option `--pepper-model` for a custom model path.
